# GENERAL SITE SETTINGS
title: Deepakumar V U
description: Personal website powered by Jekyll
baseurl: ""

# LANDING PAGE
username: Deepakumar
typing_text: '["Backend Engineer","AWS Solutions Architect Professional","Product Manager"]'
email: deepakumarvu@gmail.com
github_username: deepakumarvu
codepen_username: 
dev_username: 
linkedin_username: deepakumar-v-u
twitter_username: 

# ABOUT ME SECTION
show_aboutme_card: true
about_me_title: Who Am I
about_me_description: 

# SKILLS SECTION
show_skills_card: true
skills_title: Skills

# TIMELINE SECTION
show_timeline_card: true
timeline_title: Education & Experience
cv_download_link: https://deepakumarvu.github.io/V_U_Deepakumar_Resume.pdf

# PROJECTS SECTION
show_projects_card: true
show_projects: true
projects_title: What I have worked on
show_os_projects: false
# os_projects_title: The will be displayed as the title of your open source projects
os_projects_title: Open Source Projects

# CONTACT SECTION
show_contact_card: true
# contact_title: The will be displayed as the title in the Contact section
contact_title: Get In Touch
# contact_description: This will be displayed under the title.
contact_description: I am a Software Engineer with 6+ years of experience designing and building scalable backend systems, cloud-native applications, and secure APIs. My expertise spans Golang, AWS, and Serverless architectures, with a focus on performance, reliability, and automation. Over the years, Iâ€™ve worked on solving complex engineering challenges, optimizing infrastructure, and delivering high-impact solutions that align technology with business goals. I have recently joined Tuskira as a Senior Software Engineer, where I contribute to projects in Cybersecurity and Generative AI. I am passionate about applying my skills to cutting-edge domains, collaborating with cross-functional teams, and continuously growing as an engineer. Outside of work, I draw inspiration from long drives and exploring new places, which keeps me refreshed and creative in my problem-solving approach.

# GITHUB-METADATA
# Set this to your forked repository
# > e.g. <user>/<user>.github.io
repository: deepakumarvu/deepakumarvu.github.io
projects:
  # sortby:
  # > set this to pushed, if you want to sort your github repositories by time.
  # > set this to stars, if you want to sort your github repositories by stars.
  sort_by: pushed
  exclude:
    # archived:
    # > setting this to true, will exclude archived repositories
    # > setting this to false, will also display archived repositories
    archived: true
    # forks:
    # > setting this to true, will exclude forked repositories
    # > setting this to false, will also display forked repositories
    forks: true
    # projects: A list of the repository names you want to exclude from the listing.
    projects:
    # - repo1-to-be-excluded
    # - repo2-to-be-excluded

# GOOGLE-ANALYTICS
google-analytics:
  id: ""

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
